---
title: "Lab 10 Part 2"
author: "Justine Lang"
date: "2023-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(rvest)
library(tayloRswift)
library(tidytext)
library(ggwordcloud)
```


## Style lyrics

```{r}
url <- "https://www.songlyrics.com/taylor-swift/style-lyrics/"

style_lyrics <- read_html(url) %>% 
  html_nodes("#songLyricsDiv") %>% 
  html_text() %>% 
  str_replace_all("\n", " ") %>% 
  str_remove_all(pattern = "[[:punct:]]") %>% 
  str_to_lower() %>% 
  str_split(" ") %>% 
  as.data.frame()

colnames(style_lyrics)[1] <- "word"

lyrics <- style_lyrics %>% 
  anti_join(stop_words, by = "word")
```


## Part 2: Purrr Taylor Swift Lyrics

```{r}
load(here::here("data", "ts.Rdata"))
```


```{r}
get_lyrics <- function(artist, album, year, song){
  
  ### create url base
  base1 <- c("https://songlyrics.com/")
  base2 <- c("-lyrics")
  
  artist_url <- str_replace_all(artist, pattern = "(?!\\!)[[:punct:]]",
  replacement = " ") %>% 
    str_replace_all(pattern = " ", replacement = "-") %>% 
    str_to_lower() %>% 
    str_squish()
  
  song_url <- str_remove_all(song, pattern = "(?!\\[!'])[[:punct:]]") %>% 
    str_replace_all(pattern = "'", replacement = " ") %>% 
    str_replace_all(pattern = " ", replacement = "-") %>% 
    str_to_lower() %>% 
    str_squish()
  
  url <- paste(base1, artist_url, "/", song_url, base2, sep = "")
  
  style_lyrics <- read_html(url) %>% 
  html_nodes("#songLyricsDiv") %>% 
  html_text() %>% 
  str_replace_all("\n", " ") %>% 
  str_remove_all(pattern = "[[:punct:]]") %>% 
  str_to_lower() %>% 
  str_split(" ") %>% 
  as.data.frame() %>% 
  mutate(song=song,artist=artist,album=album,year=year)

colnames(style_lyrics)[1] <- "word"

lyrics <- style_lyrics %>% 
  anti_join(stop_words, by = "word")

return(lyrics)
  
} 

```


## Run the purrr loop

```{r}
safe_get <- safely(get_lyrics)

song_lyrics <- ts %>% 
  filter(album %in% c("1989 (Deluxe Edition)", "Speak Now (Deluxe Edition")) %>% 
  pmap(., safe_get, .progress = TRUE)

song_lyrics_flip <- transpose(song_lyrics)

any_error <- compact(song_lyrics_flip$error)

ts_lyrics <- compact(song_lyrics_flip$result) %>% 
  as_tibble_col(column_name = "word") %>% 
  unnest()

```











